import 'package:flappy_taco/widgets/game_screen/game_screen_drawers/chest_drawer_view/chest/available_prize.dart';

List<String> consolePathList = [
  'futuristicGameConsoleNoLogo2BLANKLOGO copy 3.png',
  'dotSquashGameConsoleGrey.png',
  'dotSquashGameConsoleSilver.png',
  'dotSquashGameConsoleWhite.png',
  'dotSquashGameConsoleWhiteInvert.png',
];

List<String> backgroundImageFileNames = [
  'horror41.JPG',
];

List<String> buildingBarrierFileNames = [
  'mmmZombieCombo.gif',
];

List<String> beasts = [
  'zzGhost1.gif',
  'zzBaby2.gif',
  'zzBaby.GIF',
];
List<String> grenades = [
  // 'icedGrenade1-18-23TiffanyIce.png',
  // 'icedGrenade1-18-23SaturatedBlueBlack.png',
  // 'icedGrenade1-18-23SaturatedGreenBlack.png',
  // 'icedGrenade1-18-23SaturatedLimeIce.png',
  // 'icedGrenade1-18-23SaturatedNeonGreenIce.png',
  // 'icedGrenade1-18-23SaturatedOrangeBlack.png',
  // 'icedGrenade1-18-23SaturatedOrangeIce.png',
  // 'icedGrenade1-18-23SaturatedOrangeIceX.png',
  // 'icedGrenade1-18-23SaturatedPinkBlack.png',
  // 'icedGrenade1-18-23SaturatedPinkIce.png',
  // 'icedGrenade1-18-23SaturatedPurpleBlack.png',
  // 'icedGrenade1-18-23SaturatedPurpleIce.png',
  // 'icedGrenade1-18-23SaturatedRedBlack.png',
  // 'icedGrenade1-18-23SaturatedTealBlack.png',
  // 'icedGrenade1-18-23SaturatedTealIce.png',
  // 'icedGrenade1-18-23SaturatedTurquoiseIce.png',
  // 'icedGrenade1-18-23SaturatedYellowBlack.png',
  'standardGrenade1-18-23Blue.png',
  'standardGrenade1-18-23BlueStandard3.png',
  'standardGrenade1-18-23BrightBlueInvert.png',
  'standardGrenade1-18-23BrightGreenInvert2.png',
  'standardGrenade1-18-23BrightGreenStandard.png',
  'standardGrenade1-18-23GreenRed.png',
  'standardGrenade1-18-23InvertOrange.png',
  'standardGrenade1-18-23LightGreenStandard.png',
  'standardGrenade1-18-23OrangeInvert.png',
  'standardGrenade1-18-23OrangeStandard.png',
  'standardGrenade1-18-23PinkInvert2.png',
  'standardGrenade1-18-23PinkStandard.png',
  'standardGrenade1-18-23PinkStandardWhite.png',
  'standardGrenade1-18-23PurpleInvert.png',
  'standardGrenade1-18-23RedInvert.png',
  'standardGrenade1-18-23TealStandard.png',
  'standardGrenade1-18-23YellowInvert.png',
  // 'iceGrenade1-18-23NormalCombo.gif',
  // 'iceGrenade1-18-23SaturatedCombo.gif',
  // 'SharkBomb-18-23Combo.gif',
  'standardGrenade1-18-23Combo.gif',
];
List<String> knives = [
  'bbbbPurpleBottleInvert.gif',
  'bbbbBlueKnucksInvert.gif',
  'bbbbDuctTapeKnifeInverse.gif',
  'bbbbHammerInvertBlue.gif',
  'bbbbKnuckKnifeInvert.gif',
  'bbbbMeatCleaverInvert.gif',
  'bbbbNinjaStarInvert.gif',
  'xxNinjaStar.gif',
];
List<String> guns = [
  'skeletonARPistolRemakeBlacksCombo.gif',
  'skeletonARPistolRemakeBlacksGreenCombo.gif',
  'skeletonARPistolRemakeBlacksPurpleCombo.gif',
  'skeletonARPistolRemakeBlacksYelllowCombo.gif',
  'skeletonARPistolRemakeColorfulCombos.gif',
  'skeletonARPistolRemakeWhiteBlackTealCombo.gif',
  'skeletonWhiteARPistolRemakeSkeletonHandXXX.png',
  'skeletonWhiteARPistolRemakeSkeletonHandBlack2.png',
  'skeletonWhiteARPistolRemakeSkeletonHandBluePink.png',
  'skeletonWhiteARPistolRemakeSkeletonHandBrightGreen.png',
  'skeletonWhiteARPistolRemakeSkeletonHandBrightYellow.png',
  'skeletonWhiteARPistolRemakeSkeletonHandGreen.png',
  'skeletonWhiteARPistolRemakeSkeletonHandTiffany.png',
  'skeletonWhiteARPistolRemakeSkeletonHandWhitePinkTint.png',
  'skeletonCompGunBlackxxx.png',
  'skeletonGunCompxxBlueOrange.png',
  'skeletonGunCompxxGreenNeonPink.png',
  'skeletonGunCompxxGreenPink.png',
  'skeletonGunCompxxGreenPurple.png',
  'skeletonGunCompxxInverseBlueOrangexxx.png',
  'skeletonGunCompxxInverseGreenPurple.png',
  'skeletonGunCompxxInverseNeonGreenPink.png',
  'skeletonGunCompxxInverseNeonGreenPink2.png',
  'skeletonGunCompxxInverseNeonPinkGreen.png',
  'skeletonGunCompxxInverseOrangeBlue.png',
  'skeletonGunCompxxInversePinkGreen.png',
  'skeletonGunCompxxInversePurpleGreen.png',
  'skeletonGunCompxxInverseRedGreen.png',
  'skeletonGunCompxxInverseRedWhiteBlue.png',
  'skeletonGunCompxxInverseTealYellow.png',
  'skeletonGunCompxxInverseTransGold.png',
  'skeletonGunCompxxInverseTurquoiseRed.png',
  'skeletonGunCompxxInverseWhitePinkTeal.png',
  'skeletonGunCompxxInverseYellowAndLightBlue.png',
  'skeletonGunCompxxInverseYellowBlue.png',
  'skeletonGunCompxxOrangeBlue.png',
  'skeletonGunCompxxYellowBlue.png',
  'skeletonWhiteARPistolRemakeSkeletonHand.png',
  'skeletonOpticPistolBlackNeonGreen.png',
  'skeletonOpticPistolBlackPurp.png',
  'skeletonOpticPistolBlackRed.png',
  'skeletonOpticPistolBlackSky.png',
  'skeletonOpticPistolBlackTan.png',
  'skeletonOpticPistolBlackTan2.png',
  'skeletonOpticPistolBlackTeal.png',
  'skeletonOpticPistolBlackYellow.png',
  'skeletonOpticPistolDarkPurpleOrange.png',
  'skeletonOpticPistolLightBlackGreen.png',
  'skeletonOpticPistolLightOrangeGreen.png',
  'skeletonOpticPistolLightOrangePink.png',
  'skeletonOpticPistolLightPink.png',
  'skeletonOpticPistolLightYellowBlack.png',
  'skeletonOpticPistolWhiteBlue.png',
  'skeletonDraco1.png',
  'skeletonDracoBlack.png',
  'skeletonDracoBlackBrass.png',
  'skeletonDracoBlackBrassbbb.png',
  'skeletonDracoBlackGreen.png',
  'skeletonDracoBlackGreenx.png',
  'skeletonDracoBlackGreenz.png',
  'skeletonDracoBlackOrangez.png',
  'skeletonDracoBlackPurplez.png',
  'skeletonDracoBlackRedx.png',
  'skeletonDracoBlackYellowz.png',
  'skeletonDracoBlueDark.png',
  'skeletonDracoBlueOrangeGreenbb.png',
  'skeletonDracoDarkPink.png',
  'skeletonDracoGoldPinkbbb.png',
  'skeletonDracoGreen.png',
  'skeletonDracoGreen2.png',
  'skeletonDracoInvert.png',
  'skeletonDracoOrangePink.png',
  'skeletonDracoOrangePinkx.png',
  'skeletonDracoPinkBabyBlue.png',
  'skeletonDracoPinkBlueGreenBB.png',
  'skeletonDracoPinkChrome.png',
  'skeletonDracoPinkMetal.png',
  'skeletonDracoPinkWhiteTiffanyxxx.png',
  'skeletonDracoPinkYellowBB.png',
  'skeletonDracoRed.png',
  'skeletonDracoRedBluebb.png',
  'skeletonDracoRedYellowPurplebb.png',
  'skeletonDracoWhite.png',
  'skeletonDracoWhiteBlueGreenx.png',
  'skeletonDracoWhiteGreenPinkYellow.png',
  'skeletonDracoWhitePink.png',
  'skeletonDracoWhitePink2.png',
  'skeletonDracoWhiteTurquoise.png',
  'skeletonDracoWhitexxx.png',
  'skeletonDracoYellow.png',
  'skeletonDracoYellowOrange.png',
  'skeletonDracoYellowPink.png',
  'skeletonCompGunCombo.gif',
  'skeletonDrakoCombo.gif',
  'skeletonGrenadeLauncherCombo.gif',
  'skeletonOpticPistolCombo.gif',
  'skeletonGrenadeLauncherRemakeGreen.png',
  'skeletonGrenadeLauncherRemakeHotPink.png',
  'skeletonGrenadeLauncherRemakePinkBlack.png',
  'skeletonGrenadeLauncherRemakePinkWhite.png',
  'skeletonGrenadeLauncherRemakeWhite.png',
  'skeletonGunARPistolStickMag.png',
  'skeletonGunARPistolStickMagOrange.png',
  'skeletonGunARPistolStickMagOrangeInvert.png',
  'skeletonGunARWhitePurple.png',
  'skeletonGunARWhiteTeal.png',
  'skeletonGunBlackGoldArPistol.png',
  'skeletonGunBlackGreenARPistol.png',
  'skeletonGunBlackPinkArPistol.png',
  'skeletonGunBlackPurpleArPistol.png',
  'skeletonGunBlackRedHandGun.png',
  'skeletonGunBluePistol.png',
  'skeletonGunChromeArPistol.png',
  'skeletonGunLightBlueBlackHandGun.png',
  'skeletonGunPinkPistol.png',
  'skeletonGunRedWhitePistol.png',
  'skeletonGunVector.png',
  'skeletonGunVectorBlueGreen.png',
  // 'skeletonGunVectorGrey.png',
  // 'skeletonGunVectorPinkDisturabance.png',
  // 'skeletonGunVectorPinkDisturbace2.png',
  // 'skeletonGunVectorPinkOrange.png',
  // 'skeletonGunVectorPinkPurple.png',
  // 'skeletonGunVectorPurpleBlue.png',
  // 'skeletonGunVectorRedYellowOrange.png',
  // 'skeletonGunVectorWhiteBlueInvert.png',
  'skeletonKeltechBlack.png',
  'skeletonKeltechBluedRed.png',
  'skeletonKeltechBlueGreen.png',
  'skeletonKeltechGreenedPink.png',
  'skeletonKeltechGreenPink.png',
  'skeletonKeltechGreenPurple.png',
  'skeletonKeltechOrangeGreen.png',
  'skeletonKeltechPinkBlue.png',
  'skeletonKeltechTealBrownze.png',
  'skeletonKeltechWhite.png',
  'skeletonKeltechWhiteOrangeBlue.png',
  'skeletonKeltechWhitePurpleGreen.png',
  'skeletonKeltechYellowPurple.png',
];
List<String> moreFish = [
  'blueFishSpeedUp.gif',
  'goldFishSpeedUp.gif',
  'greenFishSpeedUp.gif',
  'pinkFishSpeedUp2.gif',
  'zzFish2.GIF'
];
List<AvailablePrize> winnables = [];

List<String> faces = [
  'zzDuck.gif',
  '21Savage.gif',
  'trumpHeadxx1-22-23.gif',

  /// what about that little blue fish? That's in faces.
];
